### ISSUE TITLE
kivent_cymunk installed but Cymunk is missing

### ISSUE THREAD

**Issue by kensolano** [PureAsbestos/KivEnt-Wheels-Win64-Py3.6#1] opened 2018-04-05 16:02 UTC
Wheels installed successfully, but at the moment of testing, the following error was detected:

```
>>> import cymunk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\Python36\cymunk-master\cymunk\__init__.py", line 1, in <module>
    from .cymunk import *
ModuleNotFoundError: No module named 'cymunk.cymunk'
```

When trying to reinstall kivent_cymunk from the wheels, I get the following error:

```
C:\Python\Python36>pip install KivEnt_Cymunk-1.0.0-cp36-cp36m-win_amd64.whl
Requirement already satisfied: KivEnt-Cymunk==1.0.0 from file:///C:/Python/Python36/KivEnt_Cymunk-1.0.0-cp36-cp36m-win_amd64.whl in c:\python\python36\lib\site-packages
```
So the wheels where installed successfully, but I still don't have **Cymunk**.
I've been struggling to compile Cymunk, but nothing yet. Every time I fix an error, a new error appears.

I have the following setup:

**- Windows 10 (64 bit)**
**- Python 3.6.5**

How did you achieve to compile Cymunk?
Would you provide a precompiled version of Cymunk?

**Comment by PureAsbestos** [comment] 2018-04-10 14:22
Hi @kennethsg , it sounds like your problem is that you have a botched version of Cymunk installed that is preventing you from installing it from the wheel. Try this command:
`pip install --force KivEnt_Cymunk-1.0.0-cp36-cp36m-win_amd64.whl`
As for your other questions, I'm thinking of adding a tutorial for compiling it, and **Python wheel files are already compiled**. Also, make sure your version of Python is 64-bit.

**Comment by PureAsbestos** [comment] 2018-04-10 14:30
I almost forgot, but did you install everything in the wheels folder? specifically there is a file `cymunk-0.0.0.dev0-cp36-cp36m-win_amd64.whl` that it seems like might not be installed. As I recall, this is actually Cymunk, and KivEnt-Cymunk is a sort of glue that lets KivEnt use the Cymunk package. It's been a while. Anyway, let me know how it works.

**Comment by kensolano** [comment] 2018-04-10 14:34
Oh!
I didn't see it.
I'll try right now

**Comment by kensolano** [comment] 2018-04-10 17:05
I uninstalled all my previous Python installations and just made a fresh one:

This time I installed Cymunk from your wheel (in my previous installation I achieved to compile Cymunk with minGW, patching the cygwinccompiler.py file and adding vcruntime140.dll to the libraries).

This time I just installed Python 3.6.5, installed Kivy and finally ran the wheels.
They installed out of the box, but I'm having errors like 

`ZeroDivisionError: integer division or modulo by zero`

I was having this same errors with my previous installation of Cymunk (when I compiled it myself).

```
C:\Python36\share\kivent-examples\1_empty_kivent_app>main.py
[INFO   ] [Logger      ] Record log in C:\Users\XXXXX\.kivy\logs\kivy_18-04-10_1.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 388.43'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GTX 770M/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [AudioGstplayer] Using Gstreamer 1.10.2.0
[INFO   ] [Audio       ] Providers: audio_gstplayer, audio_sdl2 (audio_ffpyplayer ignored)
 Traceback (most recent call last):
   File "C:\Python36\share\kivent-examples\1_empty_kivent_app\main.py", line 30, in <module>
     YourAppNameApp().run()
   File "C:\Python36\lib\site-packages\kivy\app.py", line 801, in run
     self.load_kv(filename=self.kv_file)
   File "C:\Python36\lib\site-packages\kivy\app.py", line 598, in load_kv
     root = Builder.load_file(rfilename)
   File "C:\Python36\lib\site-packages\kivy\lang\builder.py", line 301, in load_file
     return self.load_string(data, **kwargs)
   File "C:\Python36\lib\site-packages\kivy\lang\builder.py", line 381, in load_string
     widget = Factory.get(parser.root.name)()
   File "C:\Python36\share\kivent-examples\1_empty_kivent_app\main.py", line 9, in __init__
     self.gameworld.init_gameworld([], callback=self.init_game)
   File "kivent_core\gameworld.pyx", line 272, in kivent_core.gameworld.GameWorld.init_gameworld
   File "kivent_core\gameworld.pyx", line 225, in kivent_core.gameworld.GameWorld.allocate
   File "kivent_core\managers\entity_manager.pyx", line 53, in kivent_core.managers.entity_manager.EntityManager.allocate
   File "kivent_core\memory_handlers\indexing.pyx", line 280, in kivent_core.memory_handlers.indexing.IndexedMemoryZone.__cinit__
   File "kivent_core\memory_handlers\zone.pyx", line 68, in kivent_core.memory_handlers.zone.MemoryZone.__cinit__
   File "kivent_core\memory_handlers\pool.pyx", line 94, in kivent_core.memory_handlers.pool.MemoryPool.__cinit__
   File "kivent_core\memory_handlers\membuffer.pyx", line 74, in kivent_core.memory_handlers.membuffer.Buffer.__cinit__
 ZeroDivisionError: integer division or modulo by zero
```

**Comment by PureAsbestos** [comment] 2018-04-10 19:15
That is a bit strange... How exactly did you install Kivy?

**Comment by PureAsbestos** [comment] 2018-04-10 19:33
As far as I can tell, it looks like there is an error in the example program. Try running a different example and see what happens.

**Comment by PureAsbestos** [comment] 2018-04-10 19:44
According to the error the problem is on line 74 in this file:
[https://github.com/kivy/kivent/blob/master/modules/core/kivent_core/memory_handlers/membuffer.pyx](url)
Which means that the variable ‘type_size’ is equal to zero... not sure why.

**Comment by PureAsbestos** [comment] 2018-04-10 20:06
Did some more tracing. ‘type_size’ is zero because gameworld.size_of_entity_block in entity_manager.pyx is zero because size_of_gameworld is zero etc. Maybe you should try another example? Anyway, I don’t think this has anything to do with my build of KivEnt so I’m going to close this issue.

**Closed as completed by PureAsbestos** 2018-04-10 20:06 UTC
Labels: question, not reproducible

**Comment by kensolano** [comment] 2018-04-10 20:12
I installed Kivy by following the procedure in the link below:

https://kivy.org/docs/installation/installation-windows.html#installation

It works out of the box with Python 3.6.5

Just copy / pasted every line of code Kivy was installed successfully.

**Comment by PureAsbestos** [comment] 2018-04-10 22:28
That sounds fine. As I said, I've closed the issue as I now believe the problem is no longer with my compilation of KivEnt/Cymunk, but some other problem that you might need to take up with the KivEnt team. If you want to give compiling for yourself a shot, check out the tutorial I just posted in this repo's wiki.
